version: '3'
services:
  golang-app:
    build:
      context: .
    container_name: golang-app
    ports:
      - "7777:8080"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - golang-app

